server:
  port: 8081

spring:
  application:
    name: apache-camel-demo

  activemq:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis

rest:
  api1: https://linkmockapi.free.beeceptor.com/customers
  api2: https://linkmockapi.free.beeceptor.com/payment